### PR TITLE
Added Some Basic Styling And Formatting

### LINKED ISSUE #2: Add Some Basic Styling
Such as colors, animate.css, and possibly some Angular Material (https://material.angularjs.org/latest/)

### PR DESCRIPTION
**Pull request by torch2424**
closes #2 

This creates a vary basic home/main page in html without any form contents. Added Angular Material, Animate.css, and some basic animations. And also, organizes our sass into separate files to be maintained individually.

This pretty much simply creates a basic skeleton for this page going forward.

Screen:

screenshot-localhost 9000 2016-02-12 13-01-31

### CODE REVIEW

**Comment by torch2424** [comment]
I was planning on a single card, page form, with a bunch of little form animation effects to look preety

**Comment by torch2424** [comment]
If anyone needs help serving let me know :) Also,  I just noticed my branch is missing the branch type, and I apologize

**Comment by rogerhoward** [comment]
Quick comments - this is more general feedback on process than specifically about this project...
1. Generally, the issue "Add some basic styling" isn't specific enough. "Implement home page design" is specific.
2. Anytime you use the word "some", try to be more specific. Eg, "Style homepage" instead of "Add some basic styling"; "Created HTML skeleton for homepage" instead of "Created some basic HTML"
3. Revisit the naming convention for branches I suggested. In this case, I your branch should be named "feature/#2-add-some-basic-styling" or, better yet, "feature/#2-implement-homepage-design". _Note_ the prefix of issue type, the slash, and the hash.

**Comment by torch2424** [comment]
Alright I will keep that in mind! And yes I noticed I named the branch incorrectly, as I named it off of memory of the rule, and my memory was wrong :( but thank you for the feedback, I shall keep that in mind :)

**Pull request merged**
